### ISSUE TITLE
I

### ISSUE THREAD

**Issue by VickyPenkova** [zuoxiang95/fashion-compatibility#2]
```
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    main()
  File "main.py", line 91, in main
    torch.distributed.init_process_group(backend="nccl")
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 148, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

**Comment by VickyPenkova** [comment]
```
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    main()
  File "main.py", line 91, in main
    torch.distributed.init_process_group(backend="nccl")
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 148, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```
